### ISSUE TITLE
adoptoposs.org down

### ISSUE THREAD

**Issue by pataquets** [adoptoposs/adoptoposs#371]
## Expected Behavior
Website to work

## Actual Behavior
``` console
$ curl -sSLI adoptoposs.org
curl: (56) Recv failure: Connection reset by peer
$ curl -sSLI https://adoptoposs.org
curl: (35) error:0A000126:SSL routines::unexpected eof while reading
$ openssl s_client -connect adoptoposs.org:443
CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 316 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
```
## Steps to Reproduce the Problem
See above

**Comment by paulgoetze** [comment]
Thanks @pataquets for opening the issue. :pray: 

There was a problem with the IPv4 entry in the DNS, since I recently changed IPv4 addresses and there were erroneous A entries.

Anyways, it's working again. There's still some issue with the login, but this is not related to this one as far as I can see (rather an issue with ueberauth).

**Comment by pataquets** [comment]
Glad to help, @paulgoetze.
Independently from where I host my public properties, I always use Cloudflare DNS service (free). Very reliable and powerful and comes packed with lots of features. they also provide domain registray at cost.
Note: I'm not affiliated with CF, just a free tier user.
