### ISSUE TITLE
Search doesn't include about/description?

### ISSUE THREAD

**Issue by abathur** [adoptoposs/adoptoposs#82]
I'm not sure if this is a bug, on the roadmap, or something you've considered and not included for good reasons, but I was playing with the new explore interface and noticed search doesn't seem to include the project about/description (it appears to just include the project `full_name`, and whatever comment the maintainer supplied when submitting):

- https://adoptoposs.org/explore?q=&f[]=4 filtered by language shell, currently showing 1 project (odb/shml).
- https://adoptoposs.org/explore?q=style&f[]=4 filtered by shell, but searches for "style", which appears in the description but produces no search result.

**Comment by paulgoetze** [comment]
Thanks for testing & reporting @abathur.

That’s a good point, we are aware of it, and it was sort of on the roadmap. I thought it might need quite a bit of changes, but I just looked briefly into it and the needed changes seem to be rather straightforward actually.  

So, my plan is, (for existing projects) to copy over the repo description from `Projects.data -> description` into a new `Project.repo_description` column and adding an index for it + (for new projects) respectively adjusting the submit-project logic.

Making the description searchable will coerce us into changing the repo description from currently markdown to plain text, in order to not allow showing results for invisible HTML tags (such as `<div>`s that currently surround each description text coming in from the GitHub API). But I figure that’s okay, given that the repo description is usually mostly plaintext with links (which could still be rendered as such).

I’ll work on it over the next days.
